# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2150d563389d3c7d1bae98ce25e0e6f88afe8561b7cb8cf44c670f37459a224ecc457200dd145e615b3271aa2e35b4dabd1ae32095799399efcf9b954c6d563c

test:
  secret_key_base: a3e623f5caa9d37c739bdd016f5da0ecaf391ec13fd4ed05732362841f5e988e2ab6c449eb65a0037c57011501e39b63f811972201996d090f66b0c4ecec7d27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
